2021-01-19 21:22:02,386 INFO    MainThread:26331 [wandb_setup.py:_flush():70] setting env: {}
2021-01-19 21:22:02,386 INFO    MainThread:26331 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-19 21:22:02,386 INFO    MainThread:26331 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-19 21:22:02,387 INFO    MainThread:26331 [wandb_init.py:_log_setup():303] Logging user logs to /home/fkubota/Git/sand-pit/028_wandb_kfold/wandb/run-20210119_212202-24ryhuc8/logs/debug.log
2021-01-19 21:22:02,387 INFO    MainThread:26331 [wandb_init.py:_log_setup():304] Logging internal logs to /home/fkubota/Git/sand-pit/028_wandb_kfold/wandb/run-20210119_212202-24ryhuc8/logs/debug-internal.log
2021-01-19 21:22:03,756 INFO    MainThread:26331 [wandb_run.py:_console_start():1237] atexit reg
2021-01-19 21:22:03,757 INFO    MainThread:26331 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-19 21:22:03,758 INFO    MainThread:26331 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-19 21:22:03,758 INFO    MainThread:26331 [redirect.py:install():204] install start
2021-01-19 21:22:03,758 INFO    MainThread:26331 [redirect.py:install():219] install stop
2021-01-19 21:22:03,758 INFO    MainThread:26331 [redirect.py:install():204] install start
2021-01-19 21:22:03,758 INFO    MainThread:26331 [redirect.py:install():219] install stop
2021-01-19 21:22:03,758 INFO    MainThread:26331 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-19 21:22:03,759 INFO    MainThread:26331 [wandb_config.py:__setitem__():135] config set dropout = 0.2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fe345b373c8>>
2021-01-19 21:22:03,759 INFO    MainThread:26331 [wandb_run.py:_config_callback():549] config_cb dropout 0.2 {'_wandb': {'cli_version': '0.10.12', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False}, 'dropout': 0.2}
2021-01-19 21:22:03,766 INFO    MainThread:26331 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 0
2021-01-19 21:22:03,767 INFO    MainThread:26331 [wandb_run.py:_restore():1179] restore
2021-01-19 21:22:03,767 INFO    MainThread:26331 [redirect.py:uninstall():223] uninstall start
2021-01-19 21:22:03,768 INFO    MainThread:26331 [redirect.py:_stop():278] _stop: stdout
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:_stop():284] _stop closed: stdout
2021-01-19 21:22:03,769 INFO    stdout    :26331 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-19 21:22:03,769 INFO    stdout    :26331 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:_stop():290] _stop joined: stdout
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:uninstall():227] uninstall done
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:uninstall():223] uninstall start
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:_stop():278] _stop: stderr
2021-01-19 21:22:03,769 INFO    MainThread:26331 [redirect.py:_stop():284] _stop closed: stderr
2021-01-19 21:22:03,769 INFO    stderr    :26331 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-19 21:22:03,770 INFO    stderr    :26331 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-19 21:22:03,770 INFO    MainThread:26331 [redirect.py:_stop():290] _stop joined: stderr
2021-01-19 21:22:03,770 INFO    MainThread:26331 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-19 21:22:03,770 INFO    MainThread:26331 [redirect.py:uninstall():227] uninstall done
2021-01-19 21:22:04,539 INFO    MainThread:26331 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "b219887edfc540cf95ab2b82c4bd4474"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 695
      total_bytes: 695
    }
  }
}

2021-01-19 21:22:06,546 INFO    MainThread:26331 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "cfd0cc648f2541ceaf479d1895f496e3"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 4371
      total_bytes: 4371
    }
  }
}

2021-01-19 21:22:07,662 INFO    MainThread:26331 [wandb_run.py:_show_summary():1469] rendering summary
2021-01-19 21:22:07,662 INFO    MainThread:26331 [wandb_run.py:_show_history():1507] rendering history
2021-01-19 21:22:07,663 INFO    MainThread:26331 [wandb_run.py:_show_files():1536] logging synced files
2021-01-19 21:22:07,665 INFO    MainThread:26331 [internal.py:handle_exit():138] Internal process exited
