2021-01-19 21:28:38,624 INFO    MainThread:28715 [wandb_setup.py:_flush():70] setting env: {}
2021-01-19 21:28:38,624 INFO    MainThread:28715 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-19 21:28:38,624 INFO    MainThread:28715 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-19 21:28:38,624 INFO    MainThread:28715 [wandb_init.py:_log_setup():303] Logging user logs to /home/fkubota/Git/sand-pit/028_wandb_kfold/wandb/run-20210119_212838-37eww69u/logs/debug.log
2021-01-19 21:28:38,624 INFO    MainThread:28715 [wandb_init.py:_log_setup():304] Logging internal logs to /home/fkubota/Git/sand-pit/028_wandb_kfold/wandb/run-20210119_212838-37eww69u/logs/debug-internal.log
2021-01-19 21:28:40,169 INFO    MainThread:28715 [wandb_run.py:_console_start():1237] atexit reg
2021-01-19 21:28:40,170 INFO    MainThread:28715 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-19 21:28:40,171 INFO    MainThread:28715 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-19 21:28:40,171 INFO    MainThread:28715 [redirect.py:install():204] install start
2021-01-19 21:28:40,171 INFO    MainThread:28715 [redirect.py:install():219] install stop
2021-01-19 21:28:40,171 INFO    MainThread:28715 [redirect.py:install():204] install start
2021-01-19 21:28:40,171 INFO    MainThread:28715 [redirect.py:install():219] install stop
2021-01-19 21:28:40,171 INFO    MainThread:28715 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-19 21:28:40,172 INFO    MainThread:28715 [wandb_config.py:__setitem__():135] config set dropout = 0.2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7efe556ac400>>
2021-01-19 21:28:40,172 INFO    MainThread:28715 [wandb_run.py:_config_callback():549] config_cb dropout 0.2 {'_wandb': {'cli_version': '0.10.12', 'python_version': '3.6.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False}, 'dropout': 0.2}
2021-01-19 21:28:40,204 INFO    MainThread:28715 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 0
2021-01-19 21:28:40,206 INFO    MainThread:28715 [wandb_run.py:_restore():1179] restore
2021-01-19 21:28:40,206 INFO    MainThread:28715 [redirect.py:uninstall():223] uninstall start
2021-01-19 21:28:40,207 INFO    MainThread:28715 [redirect.py:_stop():278] _stop: stdout
2021-01-19 21:28:40,207 INFO    stdout    :28715 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-19 21:28:40,207 INFO    MainThread:28715 [redirect.py:_stop():284] _stop closed: stdout
2021-01-19 21:28:40,208 INFO    stdout    :28715 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-19 21:28:40,208 INFO    MainThread:28715 [redirect.py:_stop():290] _stop joined: stdout
2021-01-19 21:28:40,208 INFO    MainThread:28715 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-19 21:28:40,208 INFO    MainThread:28715 [redirect.py:uninstall():227] uninstall done
2021-01-19 21:28:40,209 INFO    MainThread:28715 [redirect.py:uninstall():223] uninstall start
2021-01-19 21:28:40,209 INFO    MainThread:28715 [redirect.py:_stop():278] _stop: stderr
2021-01-19 21:28:40,210 INFO    stderr    :28715 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-19 21:28:40,210 INFO    stderr    :28715 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-19 21:28:40,210 INFO    MainThread:28715 [redirect.py:_stop():284] _stop closed: stderr
2021-01-19 21:28:40,210 INFO    MainThread:28715 [redirect.py:_stop():290] _stop joined: stderr
2021-01-19 21:28:40,210 INFO    MainThread:28715 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-19 21:28:40,210 INFO    MainThread:28715 [redirect.py:uninstall():227] uninstall done
2021-01-19 21:28:40,973 INFO    MainThread:28715 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "ee29e9df0c914e4ca79614a89dab9935"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 695
      total_bytes: 695
    }
  }
}

2021-01-19 21:28:42,980 INFO    MainThread:28715 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "b96e5eaabd754aa8b4fb298a04050451"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 4455
      total_bytes: 4455
    }
  }
}

2021-01-19 21:28:44,062 INFO    MainThread:28715 [wandb_run.py:_show_summary():1469] rendering summary
2021-01-19 21:28:44,063 INFO    MainThread:28715 [wandb_run.py:_show_history():1507] rendering history
2021-01-19 21:28:44,064 INFO    MainThread:28715 [wandb_run.py:_show_files():1536] logging synced files
2021-01-19 21:28:44,066 INFO    MainThread:28715 [internal.py:handle_exit():138] Internal process exited
